### PR TITLE
Fix endless image errors

### PR DESCRIPTION
**Pull request by patrickmcelwee**
With the current setup, `dist/images/generic.png` is not available in my
React app. I tried prepending the `node_modules` path, which also
failed.

It fails rather spectacularly, quickly generating tens of thousands of
failed network requests and console errors, eventually crashing the tab.
I think it is the issue referenced here:
https://github.com/almende/vis/issues/3338

I found that removing the `brokenImage` property worked. The nodes just
look like circles.

It would be better to figure out a framework-agnostic way to include images, but I'm not sure how to do that, and in the meantime, better to patch this issue. How did you do it in Vue? Did you set up custom image paths in the consuming app?

### CODE REVIEW

**Comment by grtjn** [comment]
AFAIK, you get that message each time a node is redrawn, and i think there is a redraw attached to window resize.

I simply added a generic.png to my public images folder. I thought i removed the dist in front. If you remove broken image and the image is not found, you get a warning. Best we can do is drop the entire default circular image shape for nodes..

**Comment by patrickmcelwee** [comment]
Fixes #21

**Comment by patrickmcelwee** [comment]
yeah, though it would be nice to find a way to include the photos from this ... for consistent styling across our demos. Also, we found that circular image worked best.

**Comment by patrickmcelwee** [comment]
updated ... I defaulted to the 'dot' shape, which looked sane.

**Comment by grtjn** [comment]
We could also drop shape entirely in favor of the default 'ellipse'..

**Comment by patrickmcelwee** [comment]
For that matter, we could remove all options. The big question is how much common `ml` stuff we want to include out of the box, for common styling decisions for our demos and apps. In this case, I agree that a dot is not a big improvement over an ellipse (although I don't love the label over the shape itself), so we might as well not have an opinion.

http://visjs.org/examples/network/nodeStyles/shapes.html

**Comment by grtjn** [comment]
Yeah, less options makes sense, but we don't specify that many.. 😉

http://visjs.org/docs/network/nodes.html#

**Pull request merged**
